CREATE VIEW ADP_EmployeeFullDailySnapshot AS
SELECT [EMPLOYEE_ID] AS [Employee ID],
    [FIRST_NAME] AS [First Name],
    [MIDDLE_NAME] AS [Middle Name],
    [LAST_NAME] AS [Last Name],
    [CURRENT_HIRE_DATE] AS [Hire Date],
    [EMPLOYEE_STATUS] AS [Employee Status],
    [TIMESHEET_CYCLE] AS [T/S Period Cd],
    [LEAVE_CYCLE] AS [Leave Cycle Cd],
    [GENERAL_LABOR_CATEGORY] AS [GLC],
    [FLSA_EXEMPT] AS [Exempt (Y/N)],
    [EMPLOYEE_TYPE] AS [Employee Type],
    [HOURLY_SALARY_STATUS] AS [Hourly/Salary Cd],
    [HOME_ORGANIZATION] AS [Organization ID],
    [DEFAULT_OT_STATE] AS [Work State Cd],
    [DEFAULT_WORKERS_COMP_CODE] AS [Workers' Compensation Cd],
    [RATE_TYPE] AS [Rate Type],
    [RATE] AS [Rate],
    [DEFAULT_LABOR_LOCATION] AS [Labor Location Cd],
    [ADDRESS_LINE_1] AS [Address Line 1],
    [ADDRESS_LINE_2] AS [Address Line 2],
    [CITY] AS [City],
    [STATE] AS [Mail State],
    [COUNTRY] AS [Country Cd],
    [POSTAL_CODE] AS [Postal Code Cd],
    [HOME_TELEPHONE] AS [Home Telephone],
    [BIRTH_DATE] AS [Birth Date],
    [GENDER] AS [Gender],
    [EMPLOYEE_CLASS] AS [Employee Class],
    [UNION_EMPLOYEE_FLAG] AS [Union Employee (Y/N)],
    [MANAGER_ID] AS [Manager Employee ID],
    [CORPORATE_OFFICER_FLAG] AS [Corporate Officer (Y/N)],
    [SEASONAL_EMPLOYEE_FLAG] AS [Season Employee (Y/N)],
    [TIMESHEET_DEFAULT_GLC] AS [Timesheet Default GLC],
    [TIMESHEET_DEFAULT_LABOR_LOCATION] AS [Timesheet Default Labor Location Cd],
    [VENDOR_ID] AS [Vendor ID],
    [WORK_EMAIL] AS [eMail ID],
    [PR_SERVICE_EMPL_ID] AS [Payroll Service Employee ID],
    [LABOR_GROUP] AS [Labor Grp Type],
    [HOME_EMAIL] AS [Home Email],
    [WORK_SCHEDULE] AS [T/C Work Schedule Cd],
    [EFFECTIVE_DATE] AS [Effective Date],
    [ESTIMATED_HOURS] AS [Work Hours in Year],
    [TERMINATION_DATE] AS [Termination Date],
    [PTO_TYPE] AS [PTO Type],
    [HOLIDAY_TYPE] AS [Holiday Type],
    [EMPLOYEE_ROLE] AS [Employee Role],
    [RACE_ETHNICITY] AS [Race/Ethnicity],
    [VOLUNTARY_TERMINATION] AS [Termination Type],
    [BENEFIT_ELIGIBLE] AS [Benefit Eligible],
    [BUSINESS_UNIT_DESCRIPTION] AS [Business Unit],
    [HOME_DEPARTMENT] AS [Home Department],
    [LEAVE_REASON_DESCRIPTION] AS [Leave Reason Description],
    [TERMINATION_REASON_DESCRIPTION] AS [Termination Reason Description],
    [HR_BUSINESS_PARTNER] AS [HR Business Partner]
FROM [MBR].[dbo].[UNIFY_ADP_FULL_DAILY_SNAPSHOT_VIEW]
